import { checkoutSessions, payments, webhookEventsData } from '../../../../lib/api';
import { Badge, Card, PageHeader, formatMoney } from '../../../../components/ui';
import { WebhookEventsList } from '../../../../components/tables';

export default function CheckoutSessionDetailPage({ params }: { params: { id: string } }) {
  const session = checkoutSessions.find((item) => item.id === params.id) ?? checkoutSessions[0];
  const payment = payments.find((item) => item.id === session.payment);
  const events = webhookEventsData.filter((event) => JSON.stringify(event.payload).includes(session.id) || (payment && JSON.stringify(event.payload).includes(payment.id)));
  return <><PageHeader title={`Session ${session.id}`} description="Détail de la session checkout, propriété marchand, paiement lié et livraisons webhook." /><div className="grid gap-6 xl:grid-cols-[1fr_0.8fr]"><Card><div className="flex items-start justify-between"><div><p className="text-sm text-slate-500">Marchand</p><h2 className="text-2xl font-semibold">{session.merchant}</h2></div><Badge value={session.status} /></div><dl className="mt-6 grid gap-4 md:grid-cols-2"><div><dt className="text-xs uppercase text-slate-400">Montant</dt><dd className="font-semibold">{formatMoney(session.amount, session.currency)}</dd></div><div><dt className="text-xs uppercase text-slate-400">Client</dt><dd>{session.customer?.name ?? '—'} · {session.customer?.email ?? '—'}</dd></div><div><dt className="text-xs uppercase text-slate-400">Expire le</dt><dd>{new Date(session.expiresAt).toLocaleString('fr-FR')}</dd></div><div><dt className="text-xs uppercase text-slate-400">Paiement lié</dt><dd>{session.payment ?? 'Aucun'}</dd></div><div><dt className="text-xs uppercase text-slate-400">Success URL</dt><dd className="break-all">{session.successUrl}</dd></div><div><dt className="text-xs uppercase text-slate-400">Cancel URL</dt><dd className="break-all">{session.cancelUrl}</dd></div></dl></Card><Card><h2 className="mb-4 font-semibold">Paiement lié</h2>{payment ? <div><p className="font-semibold">{payment.reference}</p><p className="text-sm text-slate-500">{payment.method} · {payment.provider}</p><Badge value={payment.status} /></div> : <p className="text-sm text-slate-500">Aucun paiement finalisé.</p>}</Card></div><div className="mt-6"><WebhookEventsList events={events.length ? events : webhookEventsData} /></div></>;
}
