import { apiKeys, maskSecret } from '../../../lib/api';
import { Button, Card, PageHeader } from '../../../components/ui';

const permissions = ['payments:write', 'refunds:write', 'payouts:write', 'webhooks:write', 'customers:read'];

export default function ApiKeysPage() {
  return <><PageHeader title="API Keys" description="Gérez les publishable keys et secret keys par environnement avec rotation, révocation et permissions granulaires." action={<Button>Créer une clé</Button>} />
    <div className="grid gap-5 xl:grid-cols-[1fr_0.8fr]"><Card><h2 className="mb-4 text-lg font-semibold">Nouvelle clé</h2><div className="grid gap-3 md:grid-cols-2"><input className="rounded-2xl border bg-transparent px-3 py-2" placeholder="Nom de clé"/><select className="rounded-2xl border bg-transparent px-3 py-2"><option>test</option><option>production</option></select><select className="rounded-2xl border bg-transparent px-3 py-2"><option>Secret Key</option><option>Publishable Key</option></select><Button>Générer</Button></div><div className="mt-4 grid gap-2 md:grid-cols-2">{permissions.map((permission) => <label key={permission} className="rounded-2xl border p-3 text-sm"><input type="checkbox" defaultChecked={permission.includes('read') || permission.includes('payments')} className="mr-2" />{permission}</label>)}</div></Card>
    <Card><h2 className="mb-4 text-lg font-semibold">Bonnes pratiques</h2><ul className="space-y-2 text-sm text-slate-500"><li>Utilisez <b>pk_test_</b> côté navigateur uniquement.</li><li>Utilisez <b>sk_test_</b> et <b>sk_live_</b> uniquement côté serveur.</li><li>Planifiez une rotation trimestrielle et révoquez les clés compromises.</li><li>Attribuez le minimum de permissions nécessaires à chaque intégration.</li></ul></Card></div>
    <Card className="mt-6"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-slate-400"><tr><th className="py-3">Nom</th><th>Environnement</th><th>Type</th><th>Key</th><th>Permissions</th><th>Actions</th></tr></thead><tbody>{apiKeys.map((key) => <tr key={key.id} className="border-t"><td className="py-4 font-semibold">{key.name}</td><td>{key.environment === 'live' ? 'production' : 'test'}</td><td>{key.key.startsWith('pk_') ? 'Publishable Key' : 'Secret Key'}</td><td><code>{maskSecret(key.key)}</code></td><td><span className="rounded-full bg-blue-50 px-2 py-1 text-xs text-blue-700">{key.role === 'admin' ? 'full_access' : 'restricted'}</span></td><td className="space-x-2"><button className="text-ocean">Rotation</button><button className="text-rose-600">Révoquer</button></td></tr>)}</tbody></table></div></Card>
  </>;
}
