import { metrics, payments, payouts } from '../../../lib/api';
import { PaymentsTable } from '../../../components/tables';
import { Card, formatMoney, PageHeader, StatCard } from '../../../components/ui';

export default function DashboardPage() {
  return <><PageHeader title="Vue d’ensemble" description="Suivez le solde disponible, le volume encaissé, les remboursements, les payouts et la santé de paiement." />
  <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><StatCard label="Solde disponible" value={formatMoney(metrics.balance)} detail={`${formatMoney(metrics.pending)} en attente`} accent="from-emerald-500 to-mint"/><StatCard label="Requêtes API" value={metrics.apiRequests.toLocaleString('fr-FR')} detail={`${metrics.apiErrors.toLocaleString('fr-FR')} erreurs API`} /><StatCard label="Temps réponse" value={`${metrics.responseTimeMs} ms`} detail={`${metrics.webhooksSent.toLocaleString('fr-FR')} webhooks envoyés`} accent="from-violet-500 to-blue-400"/><StatCard label="Paiements / Succès" value={metrics.paymentsCreated.toLocaleString('fr-FR')} detail={`${metrics.successRate}% taux succès`} accent="from-amber-400 to-orange-500"/></div>
  <div className="mt-6 grid gap-6 xl:grid-cols-[1.3fr_0.7fr]"><Card><h2 className="mb-6 font-semibold">Volume 12 derniers jours</h2><div className="flex h-64 items-end gap-3">{metrics.chart.map((v, i) => <div key={i} className="flex flex-1 flex-col items-center gap-2"><div className="w-full rounded-t-2xl bg-gradient-to-t from-ocean to-mint" style={{height: `${v / 1.35}%`}}/><span className="text-[10px] text-slate-400">J-{11-i}</span></div>)}</div></Card><Card><h2 className="mb-4 font-semibold">Prochains payouts</h2>{payouts.map(p => <div key={p.id} className="flex justify-between border-b py-3 last:border-0"><div><p className="font-semibold">{formatMoney(p.amount,p.currency)}</p><p className="text-xs text-slate-400">{p.destination}</p></div><p className="text-sm text-slate-500">{p.arrivalDate}</p></div>)}</Card></div>
  <div className="mt-6"><h2 className="mb-4 text-xl font-semibold">Transactions récentes</h2><PaymentsTable rows={payments.slice(0,4)} /></div></>;
}
